// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/LogoVariantA.tsx": () => import("../components/mockups/LogoVariantA.tsx"),
  "./components/mockups/LogoVariantB.tsx": () => import("../components/mockups/LogoVariantB.tsx"),
  "./components/mockups/LogoVariantC.tsx": () => import("../components/mockups/LogoVariantC.tsx")
};
